server:
  port: 8082

spring:
  mail:
    host: smtp.qq.com
    protocol: smtp
    default-encoding: UTF-8
    password: kfpenuisnytnbidh
    username: 353562631@qq.com
    port: 587
    properties:
      mail:
        stmp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
        debug: true

  rabbitmq:
    host: 1.12.217.151
    username: MrDecadent
    password: 159357la
    port: 5672
    #不指定虚拟主机的话默认/，如果账户没权限就会异常
    virtual-host: /mrd