spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 159357la
    url: jdbc:mysql://1.12.217.151:3326/vhr?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
  rabbitmq:
    host: 1.12.217.151
    username: MrDecadent
    password: 159357la
    port: 5672
    #不指定虚拟主机的话默认/，如果账户没权限就会异常
    virtual-host: /mrd

server:
  port: 8081

logging:
  level:
    com.dcd.vhr.mapper: debug
